version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pedbot
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"